services:
  nominatim:
    image: mediagis/nominatim:4.4
    container_name: nominatim
    ports:
      - "7070:8080"
    environment:
      PBF_PATH: /data/southern-zone-260127.osm.pbf
      NOMINATIM_PASSWORD: nominatim
    volumes:
      - ./nominatim/data:/data
      - ./nominatim/postgres:/var/lib/postgresql/14/main
    shm_size: 1gb
    restart: unless-stopped
    
  nextjs:
    image: node:20
    container_name: nextjs-app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs-app:/app
    depends_on:
      - nominatim
    restart: unless-stopped
